import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    core: "src/core/index.ts",
    server: "src/server.tsx",
    canvas: "src/renderers/canvas.ts",
    pieces: "src/pieces/index.ts",
    "pieces/neo": "src/pieces/sets/neo.ts",
    "pieces/cburnett": "src/pieces/sets/cburnett.ts",
    "pieces/merida": "src/pieces/sets/merida.ts",
    "pieces/alpha": "src/pieces/sets/alpha.ts",
    "pieces/chesscom": "src/pieces/sets/chesscom.ts",
    themes: "src/themes/index.ts",
    "themes/blue": "src/themes/blue.ts",
    "themes/brown": "src/themes/brown.ts",
    "themes/cafeCreme": "src/themes/cafeCreme.ts",
    "themes/canvas": "src/themes/canvas.ts",
    "themes/chesscomBlue": "src/themes/chesscomBlue.ts",
    "themes/chesscomGreen": "src/themes/chesscomGreen.ts",
    "themes/darkWood": "src/themes/darkWood.ts",
    "themes/deuteranopia": "src/themes/deuteranopia.ts",
    "themes/espresso": "src/themes/espresso.ts",
    "themes/green": "src/themes/green.ts",
    "themes/highContrast": "src/themes/highContrast.ts",
    "themes/ic": "src/themes/ic.ts",
    "themes/leather": "src/themes/leather.ts",
    "themes/marble": "src/themes/marble.ts",
    "themes/neon": "src/themes/neon.ts",
    "themes/newspaper": "src/themes/newspaper.ts",
    "themes/olive": "src/themes/olive.ts",
    "themes/pink": "src/themes/pink.ts",
    "themes/purple": "src/themes/purple.ts",
    "themes/tritanopia": "src/themes/tritanopia.ts",
    "themes/walnut": "src/themes/walnut.ts",
    "themes/wood": "src/themes/wood.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  target: "es2022",
  treeshake: true,
  minify: false,
  external: ["react", "react-dom", "web-haptics", "gigachess"],
  // Move-sound MP3s are referenced via static `new URL(..., import.meta.url)`
  // expressions and copied by the package build script. Leaving those
  // expressions intact lets consumer bundlers rebase or emit the assets.
});
